/**
 * Trading Card Game - 50 Curated Coaster Cards
 * Carefully balanced stats with variety across manufacturers and rarities
 */

import { CoasterCard, CardRarity, Manufacturer, ManufacturerPerk, PerkEffect } from './types';

/**
 * Manufacturer Perks Database
 * Special abilities for each manufacturer
 */
export const MANUFACTURER_PERKS: Record<Manufacturer, ManufacturerPerk> = {
  'intamin': {
    name: 'Launch Master',
    description: 'Speed +1 in battles',
    icon: '🚀',
    effect: {
      type: 'static',
      speedBonus: 1,
    },
  },
  'rmc': {
    name: 'Airtime Kings',
    description: 'Intensity +2 in battles',
    icon: '⚡',
    effect: {
      type: 'static',
      intensityBonus: 2,
    },
  },
  'b&m': {
    name: 'Swiss Precision',
    description: 'All stats +1',
    icon: '🎯',
    effect: {
      type: 'static',
      heightBonus: 1,
      speedBonus: 1,
      intensityBonus: 1,
    },
  },
  'arrow': {
    name: 'Classic Chaos',
    description: 'Intensity +1, Speed -1',
    icon: '🏛️',
    effect: {
      type: 'static',
      intensityBonus: 1,
      speedBonus: -1,
    },
  },
  'vekoma': {
    name: 'Underdog',
    description: '+1 to stat that would win round',
    icon: '🦾',
    effect: {
      type: 'conditional',
      special: 'Adds +1 to the stat being compared if it would win',
    },
  },
  'mack': {
    name: 'Innovation',
    description: 'Height +1 in battles',
    icon: '⚙️',
    effect: {
      type: 'static',
      heightBonus: 1,
    },
  },
  'gci': {
    name: 'Timeless',
    description: 'Intensity +2 in Round 3 only',
    icon: '🌲',
    effect: {
      type: 'conditional',
      special: '+2 to Intensity in Round 3',
    },
  },
  'giovanola': {
    name: 'Rare Breed',
    description: 'Height +1 in battles',
    icon: '⛰️',
    effect: {
      type: 'static',
      heightBonus: 1,
    },
  },
};

/**
 * The 50 Curated Coaster Cards
 * Distribution: 20 Common (40%), 15 Rare (30%), 10 Epic (20%), 5 Legendary (10%)
 */
export const ALL_CARDS: CoasterCard[] = [
  // ===== LEGENDARY CARDS (5 cards - 10%) =====
  {
    id: 'card-001',
    name: 'Fury 325',
    park: 'Carowinds',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'legendary',
    stats: { height: 9, speed: 9, intensity: 7 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Tallest and fastest giga coaster on the East Coast',
    isUnlocked: true,
  },
  {
    id: 'card-002',
    name: 'Steel Vengeance',
    park: 'Cedar Point',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'hybrid',
    rarity: 'legendary',
    stats: { height: 7, speed: 8, intensity: 10 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'Most airtime of any roller coaster in the world',
    isUnlocked: true,
  },
  {
    id: 'card-003',
    name: 'Velocicoaster',
    park: 'Universal Islands of Adventure',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'legendary',
    stats: { height: 6, speed: 8, intensity: 9 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Top hat over water at 70mph - pure adrenaline',
    isUnlocked: true,
  },
  {
    id: 'card-004',
    name: 'Intimidator 305',
    park: 'Kings Dominion',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'legendary',
    stats: { height: 9, speed: 10, intensity: 10 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Insane positive G-forces cause gray-out',
    isUnlocked: false,
  },
  {
    id: 'card-005',
    name: 'X2',
    park: 'Six Flags Magic Mountain',
    country: 'USA',
    manufacturer: 'arrow',
    type: 'steel',
    rarity: 'legendary',
    stats: { height: 7, speed: 8, intensity: 10 },
    perk: MANUFACTURER_PERKS['arrow'],
    flavor: '4th dimension coaster with rotating seats',
    isUnlocked: false,
  },

  // ===== EPIC CARDS (10 cards - 20%) =====
  {
    id: 'card-006',
    name: 'Millennium Force',
    park: 'Cedar Point',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'epic',
    stats: { height: 9, speed: 9, intensity: 7 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'First giga coaster - a legend since 2000',
    isUnlocked: true,
  },
  {
    id: 'card-007',
    name: 'Lightning Rod',
    park: 'Dollywood',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'wood',
    rarity: 'epic',
    stats: { height: 6, speed: 8, intensity: 9 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'World\'s first launched wooden coaster',
    isUnlocked: true,
  },
  {
    id: 'card-008',
    name: 'Maverick',
    park: 'Cedar Point',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'epic',
    stats: { height: 5, speed: 8, intensity: 9 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Compact intensity with beyond-vertical drop',
    isUnlocked: true,
  },
  {
    id: 'card-009',
    name: 'Twisted Colossus',
    park: 'Six Flags Magic Mountain',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'hybrid',
    rarity: 'epic',
    stats: { height: 6, speed: 7, intensity: 8 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'Dueling hybrid with High Five element',
    isUnlocked: false,
  },
  {
    id: 'card-010',
    name: 'Top Thrill 2',
    park: 'Cedar Point',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'epic',
    stats: { height: 10, speed: 10, intensity: 8 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Reborn strata coaster with LSM launch',
    isUnlocked: false,
  },
  {
    id: 'card-011',
    name: 'Phoenix',
    park: 'Knoebels',
    country: 'USA',
    manufacturer: 'gci',
    type: 'wood',
    rarity: 'epic',
    stats: { height: 3, speed: 4, intensity: 7 },
    perk: MANUFACTURER_PERKS['gci'],
    flavor: 'Classic wooden coaster with legendary airtime',
    isUnlocked: false,
  },
  {
    id: 'card-012',
    name: 'The Voyage',
    park: 'Holiday World',
    country: 'USA',
    manufacturer: 'gci',
    type: 'wood',
    rarity: 'epic',
    stats: { height: 6, speed: 7, intensity: 9 },
    perk: MANUFACTURER_PERKS['gci'],
    flavor: 'Longest wooden coaster in the United States',
    isUnlocked: false,
  },
  {
    id: 'card-013',
    name: 'Montu',
    park: 'Busch Gardens Tampa',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'epic',
    stats: { height: 5, speed: 7, intensity: 8 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Intense inverted coaster with 7 inversions',
    isUnlocked: false,
  },
  {
    id: 'card-014',
    name: 'Iron Gwazi',
    park: 'Busch Gardens Tampa',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'hybrid',
    rarity: 'epic',
    stats: { height: 7, speed: 8, intensity: 9 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'Tallest hybrid coaster in North America',
    isUnlocked: false,
  },
  {
    id: 'card-015',
    name: 'Hagrid\'s Magical Creatures',
    park: 'Universal Islands of Adventure',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'epic',
    stats: { height: 4, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Story coaster with backwards launch section',
    isUnlocked: false,
  },

  // ===== RARE CARDS (15 cards - 30%) =====
  {
    id: 'card-016',
    name: 'Banshee',
    park: 'Kings Island',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 5, speed: 7, intensity: 7 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Longest inverted coaster in the world',
    isUnlocked: true,
  },
  {
    id: 'card-017',
    name: 'Goliath',
    park: 'Six Flags Magic Mountain',
    country: 'USA',
    manufacturer: 'giovanola',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 8, speed: 8, intensity: 6 },
    perk: MANUFACTURER_PERKS['giovanola'],
    flavor: 'Massive hyper with intense helix finale',
    isUnlocked: true,
  },
  {
    id: 'card-018',
    name: 'Orion',
    park: 'Kings Island',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 9, speed: 9, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Smooth giga coaster with wave turn',
    isUnlocked: false,
  },
  {
    id: 'card-019',
    name: 'Storm Chaser',
    park: 'Kentucky Kingdom',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 5, speed: 6, intensity: 8 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'Compact RMC with triple barrel roll',
    isUnlocked: false,
  },
  {
    id: 'card-020',
    name: 'Skyrush',
    park: 'Hersheypark',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 7, speed: 8, intensity: 9 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Wing seats provide extreme negative G\'s',
    isUnlocked: false,
  },
  {
    id: 'card-021',
    name: 'Diamondback',
    park: 'Kings Island',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 7, speed: 8, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Hyper coaster with splashdown finale',
    isUnlocked: false,
  },
  {
    id: 'card-022',
    name: 'Expedition Everest',
    park: 'Disney\'s Animal Kingdom',
    country: 'USA',
    manufacturer: 'vekoma',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 6, speed: 6, intensity: 6 },
    perk: MANUFACTURER_PERKS['vekoma'],
    flavor: 'Backwards drop avoiding the Yeti',
    isUnlocked: false,
  },
  {
    id: 'card-023',
    name: 'Outlaw Run',
    park: 'Silver Dollar City',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'wood',
    rarity: 'rare',
    stats: { height: 5, speed: 7, intensity: 8 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'First wooden coaster with inversions',
    isUnlocked: false,
  },
  {
    id: 'card-024',
    name: 'Mako',
    park: 'SeaWorld Orlando',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 7, speed: 8, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Tallest and fastest coaster in Orlando',
    isUnlocked: false,
  },
  {
    id: 'card-025',
    name: 'Blue Fire',
    park: 'Europa Park',
    country: 'Germany',
    manufacturer: 'mack',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 5, speed: 7, intensity: 7 },
    perk: MANUFACTURER_PERKS['mack'],
    flavor: 'Mack\'s first launched coaster with inversions',
    isUnlocked: false,
  },
  {
    id: 'card-026',
    name: 'Wicked Cyclone',
    park: 'Six Flags New England',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'hybrid',
    rarity: 'rare',
    stats: { height: 5, speed: 7, intensity: 8 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'RMC conversion with zero-g stall',
    isUnlocked: false,
  },
  {
    id: 'card-027',
    name: 'Afterburn',
    park: 'Carowinds',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 4, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Compact inverted coaster with 6 inversions',
    isUnlocked: false,
  },
  {
    id: 'card-028',
    name: 'Copperhead Strike',
    park: 'Carowinds',
    country: 'USA',
    manufacturer: 'mack',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 4, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['mack'],
    flavor: 'Double launch with jojo roll',
    isUnlocked: false,
  },
  {
    id: 'card-029',
    name: 'Zadra',
    park: 'Energylandia',
    country: 'Poland',
    manufacturer: 'rmc',
    type: 'wood',
    rarity: 'rare',
    stats: { height: 7, speed: 8, intensity: 9 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'Tallest wooden coaster in Europe',
    isUnlocked: false,
  },
  {
    id: 'card-030',
    name: 'GateKeeper',
    park: 'Cedar Point',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'rare',
    stats: { height: 5, speed: 7, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Wing coaster through the park entrance',
    isUnlocked: false,
  },

  // ===== COMMON CARDS (20 cards - 40%) =====
  {
    id: 'card-031',
    name: 'Raptor',
    park: 'Cedar Point',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 6, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Classic inverted coaster from 1994',
    isUnlocked: true,
  },
  {
    id: 'card-032',
    name: 'Thunderhead',
    park: 'Dollywood',
    country: 'USA',
    manufacturer: 'gci',
    type: 'wood',
    rarity: 'common',
    stats: { height: 4, speed: 5, intensity: 7 },
    perk: MANUFACTURER_PERKS['gci'],
    flavor: 'Twisting wooden coaster through the forest',
    isUnlocked: true,
  },
  {
    id: 'card-033',
    name: 'Mind Bender',
    park: 'Six Flags Over Georgia',
    country: 'USA',
    manufacturer: 'arrow',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 5, intensity: 6 },
    perk: MANUFACTURER_PERKS['arrow'],
    flavor: 'Classic looping coaster from 1978',
    isUnlocked: true,
  },
  {
    id: 'card-034',
    name: 'Mystic Timbers',
    park: 'Kings Island',
    country: 'USA',
    manufacturer: 'gci',
    type: 'wood',
    rarity: 'common',
    stats: { height: 5, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['gci'],
    flavor: 'Modern wooden coaster with shed finale',
    isUnlocked: false,
  },
  {
    id: 'card-035',
    name: 'Alpengeist',
    park: 'Busch Gardens Williamsburg',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 5, speed: 7, intensity: 7 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Tallest inverted coaster in the world',
    isUnlocked: false,
  },
  {
    id: 'card-036',
    name: 'Goliath',
    park: 'Six Flags Great America',
    country: 'USA',
    manufacturer: 'rmc',
    type: 'wood',
    rarity: 'common',
    stats: { height: 5, speed: 7, intensity: 8 },
    perk: MANUFACTURER_PERKS['rmc'],
    flavor: 'Steepest wooden drop in the world',
    isUnlocked: false,
  },
  {
    id: 'card-037',
    name: 'Tennessee Tornado',
    park: 'Dollywood',
    country: 'USA',
    manufacturer: 'arrow',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['arrow'],
    flavor: 'Arrow looper through the mountains',
    isUnlocked: false,
  },
  {
    id: 'card-038',
    name: 'Griffon',
    park: 'Busch Gardens Williamsburg',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 6, speed: 7, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Dive coaster with holding brake',
    isUnlocked: false,
  },
  {
    id: 'card-039',
    name: 'Time Traveler',
    park: 'Silver Dollar City',
    country: 'USA',
    manufacturer: 'mack',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['mack'],
    flavor: 'Spinning coaster with launches and drops',
    isUnlocked: false,
  },
  {
    id: 'card-040',
    name: 'Apollo\'s Chariot',
    park: 'Busch Gardens Williamsburg',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 6, speed: 7, intensity: 5 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Hyper coaster with terrain interaction',
    isUnlocked: false,
  },
  {
    id: 'card-041',
    name: 'Verbolten',
    park: 'Busch Gardens Williamsburg',
    country: 'USA',
    manufacturer: 'intamin',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['intamin'],
    flavor: 'Launch coaster through the Black Forest',
    isUnlocked: false,
  },
  {
    id: 'card-042',
    name: 'InvadR',
    park: 'Busch Gardens Williamsburg',
    country: 'USA',
    manufacturer: 'gci',
    type: 'wood',
    rarity: 'common',
    stats: { height: 3, speed: 5, intensity: 6 },
    perk: MANUFACTURER_PERKS['gci'],
    flavor: 'Family wooden coaster with airtime',
    isUnlocked: false,
  },
  {
    id: 'card-043',
    name: 'Loch Ness Monster',
    park: 'Busch Gardens Williamsburg',
    country: 'USA',
    manufacturer: 'arrow',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 6, intensity: 5 },
    perk: MANUFACTURER_PERKS['arrow'],
    flavor: 'Interlocking loops since 1978',
    isUnlocked: false,
  },
  {
    id: 'card-044',
    name: 'Titan',
    park: 'Six Flags Over Texas',
    country: 'USA',
    manufacturer: 'giovanola',
    type: 'steel',
    rarity: 'common',
    stats: { height: 8, speed: 8, intensity: 6 },
    perk: MANUFACTURER_PERKS['giovanola'],
    flavor: 'Massive hyper with underground tunnel',
    isUnlocked: false,
  },
  {
    id: 'card-045',
    name: 'Carolina Cyclone',
    park: 'Carowinds',
    country: 'USA',
    manufacturer: 'arrow',
    type: 'steel',
    rarity: 'common',
    stats: { height: 3, speed: 5, intensity: 6 },
    perk: MANUFACTURER_PERKS['arrow'],
    flavor: 'Classic Arrow with 4 inversions',
    isUnlocked: false,
  },
  {
    id: 'card-046',
    name: 'Thunderbolt',
    park: 'Kennywood',
    country: 'USA',
    manufacturer: 'gci',
    type: 'wood',
    rarity: 'common',
    stats: { height: 3, speed: 5, intensity: 6 },
    perk: MANUFACTURER_PERKS['gci'],
    flavor: 'Historic wooden coaster from 1924',
    isUnlocked: false,
  },
  {
    id: 'card-047',
    name: 'Kumba',
    park: 'Busch Gardens Tampa',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 5, speed: 6, intensity: 7 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: '7 inversions through the jungle',
    isUnlocked: false,
  },
  {
    id: 'card-048',
    name: 'Patriot',
    park: 'Worlds of Fun',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 4, speed: 6, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'Inverted coaster converted to floorless',
    isUnlocked: false,
  },
  {
    id: 'card-049',
    name: 'Powder Keg',
    park: 'Silver Dollar City',
    country: 'USA',
    manufacturer: 'arrow',
    type: 'steel',
    rarity: 'common',
    stats: { height: 3, speed: 6, intensity: 6 },
    perk: MANUFACTURER_PERKS['arrow'],
    flavor: 'Launch coaster through Ozark hills',
    isUnlocked: false,
  },
  {
    id: 'card-050',
    name: 'Wild Eagle',
    park: 'Dollywood',
    country: 'USA',
    manufacturer: 'b&m',
    type: 'steel',
    rarity: 'common',
    stats: { height: 5, speed: 6, intensity: 6 },
    perk: MANUFACTURER_PERKS['b&m'],
    flavor: 'First wing coaster in the United States',
    isUnlocked: false,
  },
];

/**
 * Get all unlocked cards for initial collection
 */
export const getStarterCards = (): CoasterCard[] => {
  return ALL_CARDS.filter(card => card.isUnlocked);
};

/**
 * Get card by ID
 */
export const getCardById = (id: string): CoasterCard | undefined => {
  return ALL_CARDS.find(card => card.id === id);
};

/**
 * Get cards by rarity
 */
export const getCardsByRarity = (rarity: CardRarity): CoasterCard[] => {
  return ALL_CARDS.filter(card => card.rarity === rarity);
};
